vars:
  - email_spam_detection/settings.py:LocationConfig

stages:
  extract:
    cmd: poetry run python scripts/extract.py
    deps:
      - ${LocationConfig.raw_data_dir}
    outs:
      - ${LocationConfig.extracted_data_file}
  preprocess_subjects:
    cmd: poetry run python scripts/subjects.py
    deps:
      - ${LocationConfig.extracted_data_file}
    outs:
      - ${LocationConfig.subjects_data_file}
