vars:
  - email_spam_detection/settings.py:LocationConfig

stages:
  extract:
    cmd: poetry run python scripts/extract.py
    deps:
      - ${LocationConfig.raw_data_dir}
    outs:
      - ${LocationConfig.extracted_data_file}

  preprocess:
    cmd: poetry run python scripts/preprocess.py
    deps:
      - ${LocationConfig.extracted_data_file}
    outs:
      - ${LocationConfig.processed_data_file}

  prepare_cv:
    cmd: poetry run python scripts/prepare_cv.py
    deps:
      - ${LocationConfig.processed_data_file}
    outs:
      - ${LocationConfig.cv_indices_file}

  train:
    cmd: poetry run python scripts/train.py
    params:
      - email_spam_detection/settings.py:
          - TrainingConfig.input_label
          - TrainingConfig.cv_fold
          - TrainingConfig.adam_beta_1
          - TrainingConfig.adam_beta_2
          - TrainingConfig.l2_norm
